In [1]:
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [2]:
model = load_model('model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [3]:
with open('gender_encoder.pkl','rb') as file:
    gender_label_encoder = pickle.load(file)

In [4]:
with open('geography_encoder.pkl','rb') as file:
    geo_one_hot_encoder = pickle.load(file)

In [5]:
input_data = {
    'CreditScore':600,
    'Geography':'France',
    'Gender':'Male',
    'Age':40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000

}

In [13]:
test_df = pd.DataFrame([input_data])

In [14]:
test_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [15]:
geo_df = pd.DataFrame(geo_one_hot_encoder.transform(test_df[['Geography']]).toarray(),columns = geo_one_hot_encoder.get_feature_names_out())

In [16]:
geo_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [17]:
test_df = pd.concat([test_df,geo_df],axis=1)

In [18]:
test_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,France,Male,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [19]:
test_df.drop(['Geography'],axis=1,inplace=True)

In [20]:
test_df['Gender'] = gender_label_encoder.transform(test_df['Gender'])

In [21]:
test_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [22]:
with open('scaler.pkl','rb') as file:
    scaler = pickle.load(file)

In [23]:
test_df = scaler.transform(test_df)

In [24]:
test_df

array([[-0.54007722,  0.91186722,  0.10685843, -0.69164931, -0.26034447,
         0.81311138,  0.64946204,  0.96978946, -0.88017893,  1.00053348,
        -0.57776083, -0.57735027]])

In [25]:
output = model.predict(test_df)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

In [29]:
final_output = output[0][0]

In [30]:
if final_output > 0.5:
    print("The customer will churn")
else:
    print("The customer will not churn")

The customer will not churn